- name: diff
  type: category
  category:
    - Basic
    - Advanced
    - Expert
    - Master
    - Re:MASTER

- name: style
  type: category
  category:
    - Standard
    - DX
    - Festival

- name: slide_ratio
  type: numeric
  min: 0
  max: 0.5
  interval: 0.05

- name: keybr
  type: bool

- name: normal
  type: bool

- name: stars
  type: bool

- name: cc
  type: numeric
  min: 1
  max: 15
  interval: 0.1