- name: sr
  type: numeric
  min: 1
  max: 8
  interval: 0.2

- name: rank_status
  type: category
  category:
    - ranked
    - loved
    - graveyard

- name: ln_ratio
  type: numeric
  min: 0
  max: 1
  interval: 0.1

- name: rc
  type: bool

- name: hb
  type: bool

- name: ln
  type: bool

- name: ett
  type: numeric
  min: 5
  max: 35
  interval: 1

- name: stamina_ett
  type: numeric
  min: 5
  max: 35
  interval: 1

- name: stamina
  type: bool

- name: stream_ett
  type: numeric
  min: 5
  max: 35
  interval: 1

- name: stream
  type: bool

- name: jumpstream_ett
  type: numeric
  min: 5
  max: 35
  interval: 1

- name: jumpstream
  type: bool

- name: handstream_ett
  type: numeric
  min: 5
  max: 35
  interval: 1

- name: handstream
  type: bool

- name: jackspeed_ett
  type: numeric
  min: 5
  max: 35
  interval: 1

- name: jackspeed
  type: bool

- name: chordjack_ett
  type: numeric
  min: 5
  max: 35
  interval: 1

- name: chordjack
  type: bool

- name: technical_ett
  type: numeric
  min: 5
  max: 35
  interval: 1

- name: technical
  type: bool
