- name: diff
  type: category
  category:
    - EXPERT
    - MASTER
    - Re:MASTER

- name: style
  type: category
  category:
    - SD
    - DX

- name: slide_ratio
  type: numeric
  min: 0
  max: 0.5
  interval: 0.01

- name: keybr
  type: bool

- name: normal
  type: bool

- name: stars
  type: bool

- name: cc
  type: numeric
  min: 12
  max: 15
  interval: 0.1