model:
  base_learning_rate: 5e-05
  target: mug.diffusion.diffusion.DDPM
  params:
    linear_start: 0.0001
    linear_end: 0.02
    log_every_t: 100
    timesteps: 1000
    z_channels: 32
    z_length: 256
    parameterization: x0
    loss_type: l1
    ignore_keys: [ 'model.first_stage_model' ]
    monitor: val/loss_simple

    unet_config:
      target: mug.diffusion.unet.UNetModel
      params:
        in_channels: 544 # 512 + 32
        model_channels: 128
        out_channels: 32
        attention_resolutions: [ 8,4,2 ]
        num_res_blocks: 2
        channel_mult: [ 1,2,4,4 ]
        num_heads: 8
        context_dim: 128
        use_checkpoint: true

    first_stage_config:
      target: mug.firststage.autoencoder.AutoencoderKL
      params:
        monitor: "val/loss"
        ckpt_path: "/var/chenmouxiang/mug-diffusion/logs/autoencoder_kl_large/checkpoints/epoch=000999.ckpt"
        kl_weight: 0.000001
        scale: 2.0
        ddconfig:
          x_channels: 16 # key_count * 4
          middle_channels: 64
          z_channels: 32
          channel_mult: [ 1,1,2,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 1
        lossconfig:
          target: mug.firststage.losses.ManiaReconstructLoss
          params:
            weight_start_offset: 0.5
            weight_holding: 0.5
            weight_end_offset: 0.2
            label_smoothing: 0.001


    cond_stage_config:
      target: mug.cond.feature.BeatmapFeatureEmbedder
      params:
        path_to_yaml: "configs/mug/mania_beatmap_features.yaml"
        embed_dim: 128

    wave_stage_config:
      target: mug.cond.wave.STFTEncoder
      params:
        n_fft: 2048
        middle_channels: 128
        out_channels: 512
        num_res_blocks: 2
        use_checkpoint: true
        channel_mult: [ 1,2,2,2,4,4,4 ]


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: False
    num_workers: 10
    common_params:
      txt_file: "data/beatmap_4k/beatmap.txt"
      sr: 22050
      n_fft: 2048
      max_audio_frame: 16384
      n_mels: 128
      cache_dir: "data/audio_cache_stft/"
      with_audio: true
      with_feature: true
      feature_yaml: "configs/mug/mania_beatmap_features.yaml"
      # audio_window_frame = n_fft / sr / 4 = 0.02321995 s
      # note_window_frame = 2 * audio_window_frame = 0.04643990 s
      # max_duration = audio_window_frame * max_audio_frame = 380.4357 s = 6 min 20 s
      # max_note_frame = max_audio_frame / 2 = 8192
    train:
      target: mug.data.dataset.OsuTrainDataset
      params:
        mirror_p: 0.3
        feature_dropout_p: 0.5
        rate: [ 0.8,1.2 ]

    validation:
      target: mug.data.dataset.OsuValidDataset
      params: {}
#        test_txt_file: "data\\mug\\local_mania_4k_test.txt"


lightning:
  callbacks:
    beatmap_logger:
      target: mug.data.dataset.BeatmapLogger
      params:
        log_batch_idx: [ 0 ]
        splits: [ 'val' ]
        count: 16

  trainer:
    benchmark: True
    accelerator: cuda
    accumulate_grad_batches: 2
    # precision: 16
